### ISSUE TITLE
Catalina OS - internet connection problem??? simply cannot start core download

### ISSUE THREAD

**Issue by scootwise** [BlockchainCommons/GordianServer-macOS#51] opened 2020-08-18 13:55 UTC
try to start the process and immediately get this:

Error - we had an error fetching the latest version of bitcoin core. please check your internet connection and try again.

fiber connection 100Mb, internet connection is not the problem.

**Comment by Fonta1n3** [comment] 2020-08-18 14:15
> try to start the process and immediately get this:
> 
> 
> 
> 
> 
> Error - we had an error fetching the latest version of bitcoin core. please check your internet connection and try again.
> 
> 
> 
> fiber connection 100Mb, internet connection is not the problem. 

Ensure you are using the latest version (Gordian Server 0.1.2), try the dmg in the root of the repo. This is a known issue for previous versions.

**Comment by scootwise** [comment] 2020-08-18 14:17
thanks, but just checked and I’ve already got 0.1.2.

**Comment by Fonta1n3** [comment] 2020-08-18 14:35
Hmm just tap ok and use the app as normal? Could be github api acting up... we fetch latest tagged bitcoin core release from the bitcoin repo using github api

**Comment by Fonta1n3** [comment] 2020-08-18 14:38
Can you try accessing this in a browser to see if it returns valid data:


https://api.github.com/repos/bitcoin/bitcoin/tags

**Comment by scootwise** [comment] 2020-08-18 15:00
Tried that, nothing appears to be happening.
>>>Hmm just tap ok and use the app as normal? Could be github api acting up... we fetch latest tagged bitcoin core release from the bitcoin repo using github api

Here’s what comes back from that link


[
  {
    "name": "v0.20.1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.20.1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.20.1",
    "commit": {
      "sha": "7ff64311bee570874c4f0dfa18f518552188df08",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/7ff64311bee570874c4f0dfa18f518552188df08"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMjAuMQ=="
  },
  {
    "name": "v0.20.1rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.20.1rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.20.1rc1",
    "commit": {
      "sha": "cac7a9809a3d4b597fc15de16fa1e8ccdec90a8c",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/cac7a9809a3d4b597fc15de16fa1e8ccdec90a8c"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMjAuMXJjMQ=="
  },
  {
    "name": "v0.20.0",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.20.0",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.20.0",
    "commit": {
      "sha": "a62f0ed64f8bbbdfe6467ac5ce92ef5b5222d1bd",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/a62f0ed64f8bbbdfe6467ac5ce92ef5b5222d1bd"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMjAuMA=="
  },
  {
    "name": "v0.20.0rc2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.20.0rc2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.20.0rc2",
    "commit": {
      "sha": "6f7f94a276872cb4e8c0356358b479416c7dc353",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/6f7f94a276872cb4e8c0356358b479416c7dc353"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMjAuMHJjMg=="
  },
  {
    "name": "v0.20.0rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.20.0rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.20.0rc1",
    "commit": {
      "sha": "cd1f5bf1db26801a6c266ea1237734ca5ba2c64c",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/cd1f5bf1db26801a6c266ea1237734ca5ba2c64c"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMjAuMHJjMQ=="
  },
  {
    "name": "v0.19.1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.1",
    "commit": {
      "sha": "58ba7c314d552cea8cb024960a8504577aee586f",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/58ba7c314d552cea8cb024960a8504577aee586f"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMQ=="
  },
  {
    "name": "v0.19.1rc2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.1rc2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.1rc2",
    "commit": {
      "sha": "628103d673028fa59a31b885354eff1b8e04b794",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/628103d673028fa59a31b885354eff1b8e04b794"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMXJjMg=="
  },
  {
    "name": "v0.19.1rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.1rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.1rc1",
    "commit": {
      "sha": "178a8346871e17d621ac780a5c47be65508ce176",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/178a8346871e17d621ac780a5c47be65508ce176"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMXJjMQ=="
  },
  {
    "name": "v0.19.0.1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.0.1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.0.1",
    "commit": {
      "sha": "1bc9988993ee84bc814e5a7f33cc90f670a19f6a",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/1bc9988993ee84bc814e5a7f33cc90f670a19f6a"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMC4x"
  },
  {
    "name": "v0.19.0",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.0",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.0",
    "commit": {
      "sha": "42414bfd054793ca7bcf5ba329c48649e5d7933c",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/42414bfd054793ca7bcf5ba329c48649e5d7933c"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMA=="
  },
  {
    "name": "v0.19.0rc3",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.0rc3",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.0rc3",
    "commit": {
      "sha": "7358ae6d71cd0e5908a1203b61cd4e54fe4af5de",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/7358ae6d71cd0e5908a1203b61cd4e54fe4af5de"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMHJjMw=="
  },
  {
    "name": "v0.19.0rc2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.0rc2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.0rc2",
    "commit": {
      "sha": "eb5a899d5a973fe5f4700a57da82753f05138460",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/eb5a899d5a973fe5f4700a57da82753f05138460"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMHJjMg=="
  },
  {
    "name": "v0.19.0rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.19.0rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.19.0rc1",
    "commit": {
      "sha": "913972944b4f436a8afc1894352338db6b0f9561",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/913972944b4f436a8afc1894352338db6b0f9561"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTkuMHJjMQ=="
  },
  {
    "name": "v0.18.1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.1",
    "commit": {
      "sha": "fa27a0760792b251585f2a70eccdd547f915b7e4",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/fa27a0760792b251585f2a70eccdd547f915b7e4"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMQ=="
  },
  {
    "name": "v0.18.1rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.1rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.1rc1",
    "commit": {
      "sha": "a6cba19831da9de6c5f968849d07c2a006557fe4",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/a6cba19831da9de6c5f968849d07c2a006557fe4"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMXJjMQ=="
  },
  {
    "name": "v0.18.0",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.0",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.0",
    "commit": {
      "sha": "2472733a24a9364e4c6233ccd04166a26a68cc65",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/2472733a24a9364e4c6233ccd04166a26a68cc65"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMA=="
  },
  {
    "name": "v0.18.0rc4",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.0rc4",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.0rc4",
    "commit": {
      "sha": "379f71ea4f27ce0243b8b3bb87652fef76fe4ebe",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/379f71ea4f27ce0243b8b3bb87652fef76fe4ebe"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMHJjNA=="
  },
  {
    "name": "v0.18.0rc3",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.0rc3",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.0rc3",
    "commit": {
      "sha": "32ec900850446f60d13c8421c4a91f4fff912d13",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/32ec900850446f60d13c8421c4a91f4fff912d13"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMHJjMw=="
  },
  {
    "name": "v0.18.0rc2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.0rc2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.0rc2",
    "commit": {
      "sha": "d3a038200709c48922faab96d0ba558a574fa4d9",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/d3a038200709c48922faab96d0ba558a574fa4d9"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMHJjMg=="
  },
  {
    "name": "v0.18.0rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.18.0rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.18.0rc1",
    "commit": {
      "sha": "6a178e52618dff0405d2a239c9f3cc0c4582fb50",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/6a178e52618dff0405d2a239c9f3cc0c4582fb50"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTguMHJjMQ=="
  },
  {
    "name": "v0.17.2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.2",
    "commit": {
      "sha": "2f4f2d382bd77ecd768f33b9d24099528bceaaec",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/2f4f2d382bd77ecd768f33b9d24099528bceaaec"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMg=="
  },
  {
    "name": "v0.17.2rc2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.2rc2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.2rc2",
    "commit": {
      "sha": "2f4f2d382bd77ecd768f33b9d24099528bceaaec",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/2f4f2d382bd77ecd768f33b9d24099528bceaaec"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMnJjMg=="
  },
  {
    "name": "v0.17.2rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.2rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.2rc1",
    "commit": {
      "sha": "40b47d539991e6c115c047dad7909207c9b8451e",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/40b47d539991e6c115c047dad7909207c9b8451e"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMnJjMQ=="
  },
  {
    "name": "v0.17.1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.1",
    "commit": {
      "sha": "ef70f9b52b851c7997a9f1a0834714e3eebc1fd8",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/ef70f9b52b851c7997a9f1a0834714e3eebc1fd8"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMQ=="
  },
  {
    "name": "v0.17.1rc1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.1rc1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.1rc1",
    "commit": {
      "sha": "ef70f9b52b851c7997a9f1a0834714e3eebc1fd8",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/ef70f9b52b851c7997a9f1a0834714e3eebc1fd8"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMXJjMQ=="
  },
  {
    "name": "v0.17.0.1",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.0.1",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.0.1",
    "commit": {
      "sha": "1476554d3b1db5352c0de1de7524864d4bce3aac",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/1476554d3b1db5352c0de1de7524864d4bce3aac"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMC4x"
  },
  {
    "name": "v0.17.0",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.0",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.0",
    "commit": {
      "sha": "e1ed37edaedc85b8c3468bd9a726046344036243",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/e1ed37edaedc85b8c3468bd9a726046344036243"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMA=="
  },
  {
    "name": "v0.17.0rc4",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.0rc4",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.0rc4",
    "commit": {
      "sha": "c64128df5882e8dc1f76ae7c1e998ed57b8645fe",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/c64128df5882e8dc1f76ae7c1e998ed57b8645fe"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMHJjNA=="
  },
  {
    "name": "v0.17.0rc3",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.0rc3",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.0rc3",
    "commit": {
      "sha": "465a583f9dcc2383eb20bbb98bffa66fe82f2cde",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/465a583f9dcc2383eb20bbb98bffa66fe82f2cde"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMHJjMw=="
  },
  {
    "name": "v0.17.0rc2",
    "zipball_url": "https://api.github.com/repos/bitcoin/bitcoin/zipball/v0.17.0rc2",
    "tarball_url": "https://api.github.com/repos/bitcoin/bitcoin/tarball/v0.17.0rc2",
    "commit": {
      "sha": "3e4829af097b12f4255e9b04fa27c408850a783f",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/commits/3e4829af097b12f4255e9b04fa27c408850a783f"
    },
    "node_id": "MDM6UmVmMTE4MTkyNzpyZWZzL3RhZ3MvdjAuMTcuMHJjMg=="
  }
]

**Comment by Fonta1n3** [comment] 2020-08-18 15:04
@scootwise Can you send a screen grab of what you see after that alert is dismissed?

**Comment by cuongleqq** [comment] 2020-08-29 05:56
@Fonta1n3 
I have the same problem. I can access the link on my browser, but the app keeps reporting internet problem. After I hit OK on the alert, it seems that the app does not start to install things.

![image](https://user-images.githubusercontent.com/3232472/91629881-fb908300-e9f6-11ea-8a90-3fb4fdce6330.png)

**Comment by Fonta1n3** [comment] 2020-08-29 06:11
> @Fonta1n3 
> 
> I have the same problem. I can access the link on my browser, but the app keeps reporting internet problem. After I hit OK on the alert, it seems that the app does not start to install things.
> 
> 
> 
> This is the screenshot after I hit OK
> 
> ![image](https://user-images.githubusercontent.com/3232472/91629881-fb908300-e9f6-11ea-8a90-3fb4fdce6330.png)
> 
> 

What happens after you click the install button?

**Comment by cuongleqq** [comment] 2020-08-29 08:10
The error appears again like this:

![image](https://user-images.githubusercontent.com/3232472/91632229-a6aa3800-ea09-11ea-8d79-aeb6f9f8a6b8.png)

**Comment by Fonta1n3** [comment] 2020-08-29 08:32
Ok, ill be working on this in the coming week and will let you know when an update is live to test if you wouldnt mind, as I am not able to reproduce this.

**Comment by cuongleqq** [comment] 2020-08-29 08:37
Sure. If there is any log I can provide, please let me know. I am willing to test the new update too when you have it.

**Comment by Fonta1n3** [comment] 2020-09-01 08:59
@cuongleqq @scootwise I found the bug and have made a bunch of other improvements, it has not been merged yet but you can try the new notarized and pgp signed .dmg from my fork (it should get merged here asap) https://github.com/Fonta1n3/GordianServer-macOS/blob/master/GordianServer-macOS-v0.1.3.dmg

**Comment by cuongleqq** [comment] 2020-09-02 02:41
@Fonta1n3 it works well now on my machine, I can start the nodes. Though there is one minor problem that it says my half disk space is 0.0
![image](https://user-images.githubusercontent.com/3232472/91925885-26811c80-ed00-11ea-8efb-890c8865a20e.png)

**Comment by Fonta1n3** [comment] 2020-09-02 02:45
> @Fonta1n3 it works well now on my machine, I can start the nodes. Though there is one minor problem that it says my half disk space is 0.0
> 
> ![image](https://user-images.githubusercontent.com/3232472/91925885-26811c80-ed00-11ea-8efb-890c8865a20e.png)
> 
> 

Thanks! Yes thats a new feature will fix that. You can edit the prune size as described in the message if you want or disable altogether.

**Closed by Fonta1n3** 2020-09-02 02:45 UTC

**Comment by Fonta1n3** [comment] 2020-09-03 01:37
@cuongleqq what was the available disc space on your machine? I am not sure what went wrong there as I can not replicate it. It could be a permissions issue possibly where the code for checking available disc space simply fails... Did you have pruning disabled by any chance?

**Comment by Fonta1n3** [comment] 2020-09-03 01:39
Ah right, yes I can replicate that by manually editing the settings to disable pruning before doing any installation. Will fix that now, cheers.
